// This file is automatically generated by Firebase Studio.
// You can replace this with your own Firebase configuration.
// Go to your Firebase project settings, find your web app,
// and copy the firebaseConfig object here.
/* eslint-disable */
import type { FirebaseOptions } from "firebase/app";

// PASTE YOUR FIREBASE CONFIG OBJECT HERE
//
// 1. Go to your Firebase project console.
// 2. In Project settings, find your web app.
// 3. In the "SDK setup and configuration" section, copy the firebaseConfig object.
//
// Example:
// export const firebaseConfig: FirebaseOptions = {
//   apiKey: "AIzaSy...",
//   authDomain: "your-project-id.firebaseapp.com",
//   projectId: "your-project-id",
//   storageBucket: "your-project-id.appspot.com",
//   messagingSenderId: "...",
//   appId: "1:...:web:...",
//   measurementId: "G-..."
// };

export const firebaseConfig: FirebaseOptions = {
  "apiKey": "PASTE_YOUR_API_KEY_HERE",
  "authDomain": "PASTE_YOUR_AUTH_DOMAIN_HERE",
  "projectId": "PASTE_YOUR_PROJECT_ID_HERE",
  "storageBucket": "PASTE_YOUR_STORAGE_BUCKET_HERE",
  "messagingSenderId": "PASTE_YOUR_MESSAGING_SENDER_ID_HERE",
  "appId": "PASTE_YOUR_APP_ID_HERE",
  "measurementId": "PASTE_YOUR_MEASUREMENT_ID_HERE"
};
