// This file is automatically generated by Firebase Studio.
// You can replace this with your own Firebase configuration.
// Go to your Firebase project settings, find your web app,
// and copy the firebaseConfig object here.
/* eslint-disable */
import type { FirebaseOptions } from "firebase/app";

export const firebaseConfig: FirebaseOptions = {
  apiKey: "AIzaSyBxah2wopRzHoQ0KYPek_Tqo_IsD_vXMqg",
  authDomain: "dark-edge-456612-p2.firebaseapp.com",
  projectId: "dark-edge-456612-p2",
  storageBucket: "dark-edge-456612-p2.appspot.com",
  messagingSenderId: "525531950726",
  appId: "1:525531950726:web:11796cbe21204d7010ab07",
  measurementId: "G-N6LK8YSSF5"
};
