// This file is automatically generated by Firebase Studio.
// You can replace this with your own Firebase configuration.
// Go to your Firebase project settings, find your web app,
// and copy the firebaseConfig object here.
/* eslint-disable */
import type { FirebaseOptions } from "firebase/app";

// PASTE YOUR FIREBASE CONFIG OBJECT HERE
//
// 1. Go to your Firebase project console.
// 2. In Project settings, find your web app.
// 3. In the "SDK setup and configuration" section, copy the firebaseConfig object.
//
// Example:
// export const firebaseConfig: FirebaseOptions = {
//   apiKey: "AIzaSy...",
//   authDomain: "your-project-id.firebaseapp.com",
//   projectId: "your-project-id",
//   storageBucket: "your-project-id.appspot.com",
//   messagingSenderId: "...",
//   appId: "1:...:web:...",
//   measurementId: "G-..."
// };

export const firebaseConfig: FirebaseOptions = {
  apiKey: "AIzaSyBxah2wopRzHoQ0KYPek_Tqo_IsD_vXMqg",
  authDomain: "dark-edge-456612-p2.firebaseapp.com",
  projectId: "dark-edge-456612-p2",
  storageBucket: "dark-edge-456612-p2.firebasestorage.app",
  messagingSenderId: "525531950726",
  appId: "1:525531950726:web:11796cbe21204d7010ab07",
  measurementId: "G-N6LK8YSSF5"
};
